using System.Runtime.CompilerServices;
using System.Text;
using Microsoft.Data.Sqlite;

namespace Waymark.Integration.Tests;

/// <summary>
/// <c>schema_current.sql</c> is documentation of the live schema, committed and
/// never executed. <c>schema_v7_1.sql</c> is frozen at v1, so without this file
/// there is no single place to read what the database looks like now.
///
/// <para>
/// It is produced here rather than by a script, deliberately. D-019 records the
/// hazard: regenerate it from a database created by <c>dotnet ef database
/// update</c> alone and it records zero triggers as correct, forever, and every
/// later comparison agrees. This test builds the database through
/// <c>MigrateAndApplyTriggers()</c>, the same path a store uses, so the file
/// cannot be produced from a half-built database.
/// </para>
/// <para>
/// To regenerate after a migration:
/// <code>
/// $env:WAYMARK_UPDATE_SCHEMA_CURRENT = "1"
/// dotnet test src/Waymark.sln --filter FullyQualifiedName~SchemaCurrent
/// </code>
/// then read the diff before committing it. The diff is the point: it is the
/// human-readable summary of what a migration did.
/// </para>
/// </summary>
public sealed class SchemaCurrentTests : IClassFixture<MigratedDatabaseFixture>
{
    private const string UpdateVariable = "WAYMARK_UPDATE_SCHEMA_CURRENT";

    private readonly MigratedDatabaseFixture _database;

    public SchemaCurrentTests(MigratedDatabaseFixture database) => _database = database;

    /// <summary>
    /// Resolved from this source file's own location, so the test does not have
    /// to guess where the repository is from a bin directory.
    /// </summary>
    private static string SchemaCurrentPath([CallerFilePath] string thisFile = "")
    {
        var testsDirectory = Path.GetDirectoryName(thisFile)!;
        return Path.GetFullPath(Path.Combine(
            testsDirectory, "..", "..", "Waymark.Persistence", "schema_current.sql"));
    }

    /// <summary>
    /// The live schema as canonical text: tables, then indexes, then triggers,
    /// each sorted by name. Sorted so a diff shows what changed rather than
    /// what moved.
    /// </summary>
    private static string Render(SqliteConnection connection)
    {
        var text = new StringBuilder();
        text.Append(
            """
            -- =============================================================================
            -- Waymark — operational store database, current schema
            -- File: schema_current.sql
            -- =============================================================================
            --
            -- GENERATED, AND NEVER EXECUTED.
            --
            --   Regenerated by SchemaCurrentTests after every migration and committed
            --   alongside it. schema_v7_1.sql is frozen at v1, so this is the only file
            --   that shows what the database looks like now. Reading it is the point;
            --   running it is not, and it is deliberately not an embedded resource.
            --
            --   Produced from a database built by MigrateAndApplyTriggers(), which is
            --   the same path a store uses. Produced any other way it would record
            --   whatever that other way forgot — most likely the triggers.
            --
            --   To regenerate:
            --     $env:WAYMARK_UPDATE_SCHEMA_CURRENT = "1"
            --     dotnet test src/Waymark.sln --filter FullyQualifiedName~SchemaCurrent
            --
            --   EF Core's own __EFMigrationsHistory and __EFMigrationsLock are omitted:
            --   their shape is EF's business, and including them would make this file
            --   churn on an EF upgrade for no reason a reader cares about.
            --
            -- =============================================================================

            """);

        foreach (var (kind, heading) in new[]
                 {
                     ("table", "TABLES"),
                     ("index", "INDEXES"),
                     ("trigger", "TRIGGERS"),
                 })
        {
            text.Append('\n')
                .Append("-- =============================================================================\n")
                .Append("-- ").Append(heading).Append('\n')
                .Append("-- =============================================================================\n\n");

            using var command = connection.CreateCommand();
            command.CommandText = $"""
                SELECT sql FROM sqlite_schema
                WHERE type = '{kind}'
                  AND sql IS NOT NULL
                  AND name NOT LIKE 'sqlite_%'
                  AND name NOT LIKE '__EF%'
                  AND (tbl_name NOT LIKE '__EF%')
                ORDER BY name
                """;

            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                text.Append(reader.GetString(0).TrimEnd()).Append(";\n\n");
            }
        }

        return text.ToString().TrimEnd() + "\n";
    }

    [Fact]
    public void Schema_current_matches_the_database_a_store_gets()
    {
        using var connection = _database.Connect();
        var rendered = Render(connection);
        var path = SchemaCurrentPath();

        if (Environment.GetEnvironmentVariable(UpdateVariable) == "1")
        {
            File.WriteAllText(path, rendered);
            return;
        }

        Assert.True(File.Exists(path),
            $"{path} is missing. Regenerate it: set {UpdateVariable}=1 and re-run this test.");

        // Compared line by line with trailing carriage returns removed, so a
        // file checked out with CRLF does not report every line as different
        // and bury the one that actually is.
        static string[] Lines(string text) =>
            text.Split('\n').Select(line => line.TrimEnd('\r')).ToArray();

        var committedLines = Lines(File.ReadAllText(path));
        var renderedLines = Lines(rendered);

        if (committedLines.SequenceEqual(renderedLines, StringComparer.Ordinal))
        {
            return;
        }

        var length = Math.Max(committedLines.Length, renderedLines.Length);
        var differences = Enumerable.Range(0, length)
            .Where(i => (i < committedLines.Length ? committedLines[i] : null)
                        != (i < renderedLines.Length ? renderedLines[i] : null))
            .Take(5)
            .Select(i =>
                $"  line {i + 1}\n"
                + $"    committed: {(i < committedLines.Length ? committedLines[i] : "<end of file>")}\n"
                + $"    actual   : {(i < renderedLines.Length ? renderedLines[i] : "<end of file>")}");

        Assert.Fail(
            "schema_current.sql no longer describes the database. It is documentation "
            + "and has to be regenerated whenever a migration changes the schema:\n\n"
            + $"    $env:{UpdateVariable} = \"1\"\n"
            + "    dotnet test src/Waymark.sln --filter FullyQualifiedName~SchemaCurrent\n\n"
            + "then read the diff before committing it.\n\n"
            + "First differences:\n"
            + string.Join("\n", differences));
    }
}
