using Waymark.Domain.Ids;

namespace Waymark.Application.IdGenerator;

/// <summary>
/// The real one. A ULID from the current clock and a fresh 80 random bits.
///
/// <para>
/// Generated by the machine that writes, so offline terminals cannot collide
/// (CLAUDE.md §3.2). ULID rather than UUIDv4 because it sorts by creation time,
/// which keeps inserts at the end of an index instead of scattered through it.
/// </para>
/// <para>
/// <b>It sorts to millisecond resolution, not finer.</b> <c>Ulid.NewUlid()</c>
/// draws fresh randomness every call and is not monotonic within a tick, so the
/// transaction, its items, its movements and its outbox row — all minted in one
/// handler — share a timestamp and sort arbitrarily among themselves. That is
/// fine: index locality comes from the timestamp prefix, and where order
/// actually matters the schema says so in a column of its own
/// (<c>transaction_payments.sequence</c>, <c>outbox.sequence_number</c>).
/// Pinned by a test, so nobody starts relying on the stronger property.
/// </para>
/// <para>
/// Safe to register as a singleton: <c>Ulid.NewUlid()</c> is thread-safe.
/// </para>
/// </summary>
public sealed class UlidGenerator : IIdGenerator
{
    public string NewId() => Ulid.NewUlid().ToString();
}
