-- =============================================================================
-- Waymark — operational store database, current schema
-- File: schema_current.sql
-- =============================================================================
--
-- GENERATED, AND NEVER EXECUTED.
--
--   Regenerated by SchemaCurrentTests after every migration and committed
--   alongside it. schema_v7_1.sql is frozen at v1, so this is the only file
--   that shows what the database looks like now. Reading it is the point;
--   running it is not, and it is deliberately not an embedded resource.
--
--   Produced from a database built by MigrateAndApplyTriggers(), which is
--   the same path a store uses. Produced any other way it would record
--   whatever that other way forgot — most likely the triggers.
--
--   To regenerate:
--     $env:WAYMARK_UPDATE_SCHEMA_CURRENT = "1"
--     dotnet test src/Waymark.sln --filter FullyQualifiedName~SchemaCurrent
--
--   EF Core's own __EFMigrationsHistory and __EFMigrationsLock are omitted:
--   their shape is EF's business, and including them would make this file
--   churn on an EF upgrade for no reason a reader cares about.
--
-- =============================================================================

-- =============================================================================
-- TABLES
-- =============================================================================

CREATE TABLE "attribute_definitions" (
    "attribute_code" TEXT NOT NULL CONSTRAINT "PK_attribute_definitions" PRIMARY KEY,
    "label_ar" TEXT NOT NULL,
    "label_fr" TEXT NOT NULL,
    "label_en" TEXT NULL,
    "data_type" TEXT NOT NULL,
    "unit_code" TEXT NULL,
    "applies_to" TEXT NOT NULL,
    "is_groupable" INTEGER NOT NULL DEFAULT 0,
    "is_filterable" INTEGER NOT NULL DEFAULT 0,
    "help_text" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_attribute_definitions_applies_to" CHECK (applies_to IN ('product','variant')),
    CONSTRAINT "ck_attribute_definitions_data_type" CHECK (data_type IN ('text','number','bool','date','enum')),
    CONSTRAINT "ck_attribute_definitions_is_filterable" CHECK (is_filterable IN (0,1)),
    CONSTRAINT "ck_attribute_definitions_is_groupable" CHECK (is_groupable IN (0,1)),
    CONSTRAINT "ck_attribute_definitions_status" CHECK (status IN ('active','archived')),
    CONSTRAINT "ck_attribute_definitions_unit_code" CHECK (unit_code IS NULL OR data_type = 'number'),
    CONSTRAINT "FK_attribute_definitions_units_of_measure_unit_code" FOREIGN KEY ("unit_code") REFERENCES "units_of_measure" ("unit_code")
) STRICT;

CREATE TABLE "attribute_options" (
    "attribute_code" TEXT NOT NULL,
    "option_code" TEXT NOT NULL,
    "label_ar" TEXT NOT NULL,
    "label_fr" TEXT NOT NULL,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "PK_attribute_options" PRIMARY KEY ("attribute_code", "option_code"),
    CONSTRAINT "ck_attribute_options_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "FK_attribute_options_attribute_definitions_attribute_code" FOREIGN KEY ("attribute_code") REFERENCES "attribute_definitions" ("attribute_code") ON DELETE CASCADE
) STRICT;

CREATE TABLE "batch_items" (
    "batch_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "quantity_received" INTEGER NOT NULL,
    "unit_code" TEXT NOT NULL,
    "unit_cost" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "created_at" TEXT NOT NULL,
    CONSTRAINT "PK_batch_items" PRIMARY KEY ("batch_id", "variant_id"),
    CONSTRAINT "ck_batch_items_quantity_received" CHECK (quantity_received > 0),
    CONSTRAINT "ck_batch_items_unit_cost" CHECK (unit_cost >= 0),
    CONSTRAINT "FK_batch_items_units_of_measure_unit_code" FOREIGN KEY ("unit_code") REFERENCES "units_of_measure" ("unit_code"),
    CONSTRAINT "FK_batch_items_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id"),
    CONSTRAINT "FK_batch_items_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id")
) STRICT;

CREATE TABLE "batches" (
    "batch_id" TEXT NOT NULL CONSTRAINT "PK_batches" PRIMARY KEY,
    "lot_number" TEXT NULL,
    "supplier_document_ref" TEXT NULL,
    "product_id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "supplier_id" TEXT NULL,
    "order_id" TEXT NULL,
    "received_date" TEXT NOT NULL,
    "expiration_date" TEXT NULL,
    "received_by" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_batches_expiration_date" CHECK (expiration_date IS NULL OR expiration_date >= received_date),
    CONSTRAINT "ck_batches_status" CHECK (status IN ('active','depleted','written_off','quarantined')),
    CONSTRAINT "FK_batches_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id"),
    CONSTRAINT "FK_batches_suppliers_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id"),
    CONSTRAINT "FK_batches_purchase_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "purchase_orders" ("order_id"),
    CONSTRAINT "FK_batches_staff_received_by" FOREIGN KEY ("received_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_batches_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "cash_movements" (
    "movement_id" TEXT NOT NULL CONSTRAINT "PK_cash_movements" PRIMARY KEY,
    "session_id" TEXT NOT NULL,
    "movement_type" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "reason_code" TEXT NOT NULL,
    "note" TEXT NULL,
    "staff_id" TEXT NOT NULL,
    "authorised_by" TEXT NULL,
    "occurred_at" TEXT NOT NULL,
    CONSTRAINT "ck_cash_movements_amount" CHECK (amount > 0),
    CONSTRAINT "ck_cash_movements_movement_type" CHECK (movement_type IN ('paid_in','paid_out','drop','float_add','float_remove')),
    CONSTRAINT "FK_cash_movements_reason_codes_reason_code" FOREIGN KEY ("reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_cash_movements_cash_sessions_session_id" FOREIGN KEY ("session_id") REFERENCES "cash_sessions" ("session_id"),
    CONSTRAINT "FK_cash_movements_staff_authorised_by" FOREIGN KEY ("authorised_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_cash_movements_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id")
) STRICT;

CREATE TABLE "cash_sessions" (
    "session_id" TEXT NOT NULL CONSTRAINT "PK_cash_sessions" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "terminal_id" TEXT NOT NULL,
    "opened_by" TEXT NOT NULL,
    "opened_at" TEXT NOT NULL,
    "opening_float" INTEGER NOT NULL DEFAULT 0,
    "closed_by" TEXT NULL,
    "closed_at" TEXT NULL,
    "counted_cash" INTEGER NULL,
    "expected_cash" INTEGER NULL,
    "variance" INTEGER NULL,
    "z_report_number" INTEGER NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "notes" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_cash_sessions_closed_at" CHECK (closed_at IS NULL OR closed_at >= opened_at),
    CONSTRAINT "ck_cash_sessions_status" CHECK (status IN ('open','closed','suspended')),
    CONSTRAINT "ck_cash_sessions_status_2" CHECK (status <> 'closed' OR counted_cash IS NOT NULL),
    CONSTRAINT "FK_cash_sessions_staff_closed_by" FOREIGN KEY ("closed_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_cash_sessions_staff_opened_by" FOREIGN KEY ("opened_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_cash_sessions_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_cash_sessions_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id")
) STRICT;

CREATE TABLE "categories" (
    "category_id" TEXT NOT NULL CONSTRAINT "PK_categories" PRIMARY KEY,
    "category_name" TEXT NOT NULL,
    "parent_id" TEXT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT NULL,
    "image" TEXT NULL,
    "tax_rate" INTEGER NULL,
    "sensitive_flag" INTEGER NOT NULL DEFAULT 0,
    "sensitive_reason" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_categories_parent_id" CHECK (parent_id IS NULL OR parent_id <> category_id),
    CONSTRAINT "ck_categories_sensitive_flag" CHECK (sensitive_flag IN (0,1)),
    CONSTRAINT "ck_categories_sensitive_flag_2" CHECK (sensitive_flag = 0 OR sensitive_reason IS NOT NULL),
    CONSTRAINT "ck_categories_status" CHECK (status IN ('active','archived')),
    CONSTRAINT "ck_categories_tax_rate" CHECK (tax_rate IS NULL OR tax_rate BETWEEN 0 AND 10000),
    CONSTRAINT "FK_categories_categories_parent_id" FOREIGN KEY ("parent_id") REFERENCES "categories" ("category_id")
) STRICT;

CREATE TABLE "category_attributes" (
    "category_id" TEXT NOT NULL,
    "attribute_code" TEXT NOT NULL,
    "is_required" INTEGER NOT NULL DEFAULT 0,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "inherits_to_children" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "PK_category_attributes" PRIMARY KEY ("category_id", "attribute_code"),
    CONSTRAINT "ck_category_attributes_inherits_to_children" CHECK (inherits_to_children IN (0,1)),
    CONSTRAINT "ck_category_attributes_is_required" CHECK (is_required IN (0,1)),
    CONSTRAINT "FK_category_attributes_attribute_definitions_attribute_code" FOREIGN KEY ("attribute_code") REFERENCES "attribute_definitions" ("attribute_code") ON DELETE CASCADE,
    CONSTRAINT "FK_category_attributes_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "consent_events" (
    "consent_event_id" TEXT NOT NULL CONSTRAINT "PK_consent_events" PRIMARY KEY,
    "customer_id" TEXT NOT NULL,
    "occurred_at" TEXT NOT NULL,
    "action" TEXT NOT NULL,
    "consent_type" TEXT NOT NULL,
    "notice_version" TEXT NOT NULL,
    "captured_by" TEXT NULL,
    "method" TEXT NOT NULL,
    "terminal_id" TEXT NULL,
    CONSTRAINT "ck_consent_events_action" CHECK (action IN ('granted','withdrawn','renewed')),
    CONSTRAINT "ck_consent_events_consent_type" CHECK (consent_type IN ('processing','marketing')),
    CONSTRAINT "ck_consent_events_method" CHECK (method IN ('verbal','written','digital')),
    CONSTRAINT "FK_consent_events_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id"),
    CONSTRAINT "FK_consent_events_notice_versions_notice_version" FOREIGN KEY ("notice_version") REFERENCES "notice_versions" ("version_code"),
    CONSTRAINT "FK_consent_events_staff_captured_by" FOREIGN KEY ("captured_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_consent_events_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id")
) STRICT;

CREATE TABLE "credit_movements" (
    "movement_id" TEXT NOT NULL CONSTRAINT "PK_credit_movements" PRIMARY KEY,
    "customer_id" TEXT NOT NULL,
    "movement_type" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "balance_after" INTEGER NOT NULL,
    "transaction_id" TEXT NULL,
    "return_id" TEXT NULL,
    "expires_at" TEXT NULL,
    "staff_id" TEXT NULL,
    "terminal_id" TEXT NULL,
    "reason_code" TEXT NULL,
    "note" TEXT NULL,
    "occurred_at" TEXT NOT NULL,
    CONSTRAINT "ck_credit_movements_amount" CHECK (amount <> 0),
    CONSTRAINT "ck_credit_movements_movement_type" CHECK (movement_type IN ('issue','redeem','adjust','expire','reverse')),
    CONSTRAINT "FK_credit_movements_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id"),
    CONSTRAINT "FK_credit_movements_reason_codes_reason_code" FOREIGN KEY ("reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_credit_movements_returns_return_id" FOREIGN KEY ("return_id") REFERENCES "returns" ("return_id"),
    CONSTRAINT "FK_credit_movements_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_credit_movements_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id"),
    CONSTRAINT "FK_credit_movements_transactions_transaction_id" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id")
) STRICT;

CREATE TABLE "customers" (
    "customer_id" TEXT NOT NULL CONSTRAINT "PK_customers" PRIMARY KEY,
    "customer_name" TEXT NOT NULL,
    "contact_phone" TEXT NULL,
    "email" TEXT NULL,
    "preferred_language" TEXT NOT NULL DEFAULT 'ar',
    "join_date" TEXT NOT NULL,
    "last_order_date" TEXT NULL,
    "points" INTEGER NOT NULL DEFAULT 0,
    "credit" INTEGER NOT NULL DEFAULT 0,
    "discount" INTEGER NOT NULL DEFAULT 0,
    "tier_ranking" TEXT NULL,
    "ecommerce_flag" INTEGER NOT NULL DEFAULT 0,
    "legal_basis" TEXT NOT NULL DEFAULT 'contract',
    "consent_profiling" INTEGER NOT NULL DEFAULT 0,
    "consent_profiling_at" TEXT NULL,
    "consent_profiling_notice_version" TEXT NULL,
    "consent_marketing" INTEGER NOT NULL DEFAULT 0,
    "consent_marketing_at" TEXT NULL,
    "consent_marketing_notice_version" TEXT NULL,
    "objection_flag" INTEGER NOT NULL DEFAULT 0,
    "deletion_requested_at" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_customers_consent_marketing" CHECK (consent_marketing IN (0,1)),
    CONSTRAINT "ck_customers_consent_marketing_2" CHECK (consent_marketing = 0 OR consent_marketing_at IS NOT NULL),
    CONSTRAINT "ck_customers_consent_profiling" CHECK (consent_profiling IN (0,1)),
    CONSTRAINT "ck_customers_consent_profiling_2" CHECK (consent_profiling = 0 OR consent_profiling_at IS NOT NULL),
    CONSTRAINT "ck_customers_discount" CHECK (discount BETWEEN 0 AND 10000),
    CONSTRAINT "ck_customers_ecommerce_flag" CHECK (ecommerce_flag IN (0,1)),
    CONSTRAINT "ck_customers_legal_basis" CHECK (legal_basis IN ('consent','contract','legal_obligation','legitimate_interest')),
    CONSTRAINT "ck_customers_objection_flag" CHECK (objection_flag IN (0,1)),
    CONSTRAINT "ck_customers_preferred_language" CHECK (preferred_language IN ('ar','fr','en')),
    CONSTRAINT "ck_customers_status" CHECK (status IN ('active','inactive','erased')),
    CONSTRAINT "FK_customers_notice_versions_consent_marketing_notice_version" FOREIGN KEY ("consent_marketing_notice_version") REFERENCES "notice_versions" ("version_code"),
    CONSTRAINT "FK_customers_notice_versions_consent_profiling_notice_version" FOREIGN KEY ("consent_profiling_notice_version") REFERENCES "notice_versions" ("version_code")
) STRICT;

CREATE TABLE "data_subject_requests" (
    "request_id" TEXT NOT NULL CONSTRAINT "PK_data_subject_requests" PRIMARY KEY,
    "customer_id" TEXT NOT NULL,
    "request_type" TEXT NOT NULL,
    "received_at" TEXT NOT NULL,
    "due_at" TEXT NOT NULL,
    "received_by" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "resolution_note" TEXT NULL,
    "resolved_at" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_data_subject_requests_request_type" CHECK (request_type IN ('information','access','rectification','objection','erasure')),
    CONSTRAINT "ck_data_subject_requests_status" CHECK (status IN ('open','in_progress','fulfilled','refused','blocked')),
    CONSTRAINT "ck_data_subject_requests_status_2" CHECK (status NOT IN ('refused','blocked') OR resolution_note IS NOT NULL),
    CONSTRAINT "FK_data_subject_requests_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id"),
    CONSTRAINT "FK_data_subject_requests_staff_received_by" FOREIGN KEY ("received_by") REFERENCES "staff" ("staff_id")
) STRICT;

CREATE TABLE "erasure_ledger" (
    "erasure_id" TEXT NOT NULL CONSTRAINT "PK_erasure_ledger" PRIMARY KEY,
    "subject_type" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "request_id" TEXT NULL,
    "requested_at" TEXT NOT NULL,
    "executed_at" TEXT NULL,
    "executed_by" TEXT NULL,
    "scope_json" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "blocked_reason" TEXT NULL,
    "cloud_confirmed_at" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_erasure_ledger_status" CHECK (status IN ('pending','executed','blocked')),
    CONSTRAINT "ck_erasure_ledger_status_2" CHECK (status <> 'blocked' OR blocked_reason IS NOT NULL),
    CONSTRAINT "ck_erasure_ledger_status_3" CHECK (status <> 'executed' OR executed_at IS NOT NULL),
    CONSTRAINT "ck_erasure_ledger_subject_type" CHECK (subject_type IN ('customer','staff')),
    CONSTRAINT "FK_erasure_ledger_data_subject_requests_request_id" FOREIGN KEY ("request_id") REFERENCES "data_subject_requests" ("request_id"),
    CONSTRAINT "FK_erasure_ledger_staff_executed_by" FOREIGN KEY ("executed_by") REFERENCES "staff" ("staff_id")
) STRICT;

CREATE TABLE "inbox" (
    "inbox_id" TEXT NOT NULL CONSTRAINT "PK_inbox" PRIMARY KEY,
    "message_id" TEXT NOT NULL,
    "cloud_sequence" INTEGER NOT NULL,
    "channel" TEXT NOT NULL,
    "message_type" TEXT NOT NULL,
    "payload_json" TEXT NOT NULL,
    "received_at" TEXT NOT NULL,
    "applied_at" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "rejection_reason" TEXT NULL,
    CONSTRAINT "ck_inbox_channel" CHECK (channel IN ('C_recommendations','D_intents','E_control','F_parameters')),
    CONSTRAINT "ck_inbox_status" CHECK (status IN ('pending','applied','duplicate','rejected'))
) STRICT;

CREATE TABLE "intents" (
    "intent_id" TEXT NOT NULL CONSTRAINT "PK_intents" PRIMARY KEY,
    "intent_type" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "payload_json" TEXT NOT NULL,
    "preconditions_json" TEXT NOT NULL,
    "created_at_cloud" TEXT NOT NULL,
    "expires_at" TEXT NULL,
    "received_at" TEXT NOT NULL,
    "evaluated_at" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "rejection_reason" TEXT NULL,
    "fresh_request_id" TEXT NULL,
    "decided_by_cloud_user" TEXT NULL,
    CONSTRAINT "ck_intents_intent_type" CHECK (intent_type IN ('accept_reorder','markdown_stage','adjust_quantity','dismiss', 'price_change','promotion','catalogue_edit','supplier_edit', 'rights_action')),
    CONSTRAINT "ck_intents_status" CHECK (status IN ('pending','applied','rejected_stale','rejected_invalid')),
    CONSTRAINT "ck_intents_status_2" CHECK (status NOT IN ('rejected_stale','rejected_invalid') OR rejection_reason IS NOT NULL),
    CONSTRAINT "FK_intents_recommendations_fresh_request_id" FOREIGN KEY ("fresh_request_id") REFERENCES "recommendations" ("recommendation_id"),
    CONSTRAINT "FK_intents_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "inventories" (
    "store_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "batch_id" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL DEFAULT 0,
    "reserved_quantity" INTEGER NOT NULL DEFAULT 0,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "PK_inventories" PRIMARY KEY ("store_id", "variant_id", "batch_id"),
    CONSTRAINT "ck_inventories_reserved_quantity" CHECK (reserved_quantity >= 0),
    CONSTRAINT "FK_inventories_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id"),
    CONSTRAINT "FK_inventories_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id"),
    CONSTRAINT "FK_inventories_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "loyalty_movements" (
    "movement_id" TEXT NOT NULL CONSTRAINT "PK_loyalty_movements" PRIMARY KEY,
    "customer_id" TEXT NOT NULL,
    "movement_type" TEXT NOT NULL,
    "points" INTEGER NOT NULL,
    "balance_after" INTEGER NOT NULL,
    "transaction_id" TEXT NULL,
    "staff_id" TEXT NULL,
    "terminal_id" TEXT NULL,
    "reason_code" TEXT NULL,
    "note" TEXT NULL,
    "occurred_at" TEXT NOT NULL,
    CONSTRAINT "ck_loyalty_movements_movement_type" CHECK (movement_type IN ('earn','redeem','adjust','expire','reverse')),
    CONSTRAINT "ck_loyalty_movements_points" CHECK (points <> 0),
    CONSTRAINT "FK_loyalty_movements_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id"),
    CONSTRAINT "FK_loyalty_movements_reason_codes_reason_code" FOREIGN KEY ("reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_loyalty_movements_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_loyalty_movements_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id"),
    CONSTRAINT "FK_loyalty_movements_transactions_transaction_id" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id")
) STRICT;

CREATE TABLE "notice_versions" (
    "version_code" TEXT NOT NULL CONSTRAINT "PK_notice_versions" PRIMARY KEY,
    "notice_type" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "body_text" TEXT NOT NULL,
    "effective_from" TEXT NOT NULL,
    "effective_to" TEXT NULL,
    "published_at" TEXT NOT NULL,
    CONSTRAINT "ck_notice_versions_effective_to" CHECK (effective_to IS NULL OR effective_to > effective_from),
    CONSTRAINT "ck_notice_versions_language" CHECK (language IN ('ar','fr','en')),
    CONSTRAINT "ck_notice_versions_notice_type" CHECK (notice_type IN ('processing','marketing','staff'))
) STRICT;

CREATE TABLE "outbox" (
    "outbox_id" TEXT NOT NULL CONSTRAINT "PK_outbox" PRIMARY KEY,
    "sequence_number" INTEGER NOT NULL,
    "channel" TEXT NOT NULL,
    "message_type" TEXT NOT NULL,
    "entity_type" TEXT NULL,
    "entity_id" TEXT NULL,
    "payload_json" TEXT NOT NULL,
    "is_priority" INTEGER NOT NULL DEFAULT 0,
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "last_attempt_at" TEXT NULL,
    "last_error" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_outbox_channel" CHECK (channel IN ('A_statistics','B_operational','D_decisions')),
    CONSTRAINT "ck_outbox_is_priority" CHECK (is_priority IN (0,1))
) STRICT;

CREATE TABLE "parameter_registry" (
    "parameter_code" TEXT NOT NULL,
    "scope_type" TEXT NOT NULL,
    "scope_id" TEXT NOT NULL DEFAULT '',
    "version" INTEGER NOT NULL,
    "value_number" INTEGER NULL,
    "value_text" TEXT NULL,
    "unit_code" TEXT NULL,
    "interval_low" INTEGER NULL,
    "interval_high" INTEGER NULL,
    "method" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "observation_count" INTEGER NOT NULL DEFAULT 0,
    "computed_at" TEXT NOT NULL,
    "is_current" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "PK_parameter_registry" PRIMARY KEY ("parameter_code", "scope_type", "scope_id", "version"),
    CONSTRAINT "ck_parameter_registry_interval_low" CHECK (interval_low IS NULL OR interval_high IS NULL OR interval_high >= interval_low),
    CONSTRAINT "ck_parameter_registry_is_current" CHECK (is_current IN (0,1)),
    CONSTRAINT "ck_parameter_registry_scope_type" CHECK (scope_type IN ('global','store','category','variant','supplier')),
    CONSTRAINT "ck_parameter_registry_source" CHECK (source IN ('engine','cold_start_default','manual_override')),
    CONSTRAINT "ck_parameter_registry_value_number" CHECK (value_number IS NOT NULL OR value_text IS NOT NULL),
    CONSTRAINT "FK_parameter_registry_units_of_measure_unit_code" FOREIGN KEY ("unit_code") REFERENCES "units_of_measure" ("unit_code")
) STRICT;

CREATE TABLE "prices" (
    "variant_id" TEXT NOT NULL,
    "valid_from" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "price_type" TEXT NOT NULL DEFAULT 'retail',
    "price" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "is_tax_inclusive" INTEGER NOT NULL DEFAULT 1,
    "valid_to" TEXT NULL,
    "created_by" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "PK_prices" PRIMARY KEY ("variant_id", "valid_from", "store_id", "price_type"),
    CONSTRAINT "ck_prices_is_tax_inclusive" CHECK (is_tax_inclusive IN (0,1)),
    CONSTRAINT "ck_prices_price" CHECK (price >= 0),
    CONSTRAINT "ck_prices_price_type" CHECK (price_type IN ('retail','wholesale','staff','promotional')),
    CONSTRAINT "ck_prices_valid_to" CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT "FK_prices_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id"),
    CONSTRAINT "FK_prices_staff_created_by" FOREIGN KEY ("created_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_prices_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "processing_counters" (
    "counter_id" TEXT NOT NULL CONSTRAINT "PK_processing_counters" PRIMARY KEY,
    "store_id" TEXT NULL,
    "day" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "purpose" TEXT NOT NULL,
    "event_count" INTEGER NOT NULL,
    "rolled_up_at" TEXT NOT NULL,
    CONSTRAINT "ck_processing_counters_event_count" CHECK (event_count > 0),
    CONSTRAINT "FK_processing_counters_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "processing_log" (
    "log_id" TEXT NOT NULL CONSTRAINT "PK_processing_log" PRIMARY KEY,
    "occurred_at" TEXT NOT NULL,
    "operation" TEXT NOT NULL,
    "subject_type" TEXT NOT NULL,
    "subject_id" TEXT NULL,
    "actor_type" TEXT NOT NULL,
    "actor_id" TEXT NULL,
    "purpose" TEXT NOT NULL,
    "recipient" TEXT NULL,
    "source_module" TEXT NOT NULL,
    "store_id" TEXT NULL,
    "terminal_id" TEXT NULL, "legal_basis" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "ck_processing_log_actor_type" CHECK (actor_type IN ('staff','system','engine')),
    CONSTRAINT "ck_processing_log_operation" CHECK (operation IN ('collection','consultation','disclosure','transmission', 'modification','erasure','pseudonymisation','re_identification')),
    CONSTRAINT "ck_processing_log_subject_type" CHECK (subject_type IN ('customer','staff')),
    CONSTRAINT "FK_processing_log_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_processing_log_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id")
) STRICT;

CREATE TABLE "product_attribute_values" (
    "product_id" TEXT NOT NULL,
    "attribute_code" TEXT NOT NULL,
    "value_text" TEXT NULL,
    "value_number" INTEGER NULL,
    "value_bool" INTEGER NULL,
    "value_date" TEXT NULL,
    "option_code" TEXT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "PK_product_attribute_values" PRIMARY KEY ("product_id", "attribute_code"),
    CONSTRAINT "ck_product_attribute_values_CASE" CHECK ((CASE WHEN value_text IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_number IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_bool IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_date IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN option_code IS NOT NULL THEN 1 ELSE 0 END) = 1),
    CONSTRAINT "ck_product_attribute_values_value_bool" CHECK (value_bool IS NULL OR value_bool IN (0,1)),
    CONSTRAINT "FK_product_attribute_values_attribute_definitions_attribute_code" FOREIGN KEY ("attribute_code") REFERENCES "attribute_definitions" ("attribute_code"),
    CONSTRAINT "FK_product_attribute_values_attribute_options_attribute_code_option_code" FOREIGN KEY ("attribute_code", "option_code") REFERENCES "attribute_options" ("attribute_code", "option_code"),
    CONSTRAINT "FK_product_attribute_values_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "product_bundle_items" (
    "bundle_item_id" TEXT NOT NULL CONSTRAINT "PK_product_bundle_items" PRIMARY KEY,
    "bundle_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "valid_from" TEXT NOT NULL,
    "valid_to" TEXT NULL,
    "description" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    CONSTRAINT "ck_product_bundle_items_quantity" CHECK (quantity > 0),
    CONSTRAINT "ck_product_bundle_items_status" CHECK (status IN ('active','inactive')),
    CONSTRAINT "ck_product_bundle_items_valid_to" CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT "FK_product_bundle_items_product_bundles_bundle_id" FOREIGN KEY ("bundle_id") REFERENCES "product_bundles" ("bundle_id") ON DELETE CASCADE,
    CONSTRAINT "FK_product_bundle_items_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id")
) STRICT;

CREATE TABLE "product_bundles" (
    "bundle_id" TEXT NOT NULL CONSTRAINT "PK_product_bundles" PRIMARY KEY,
    "barcode" TEXT NULL,
    "bundle_name" TEXT NOT NULL,
    "bundle_type" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_product_bundles_bundle_type" CHECK (bundle_type IN ('fixed','mix_and_match')),
    CONSTRAINT "ck_product_bundles_status" CHECK (status IN ('active','inactive','archived'))
) STRICT;

CREATE TABLE "product_category" (
    "product_id" TEXT NOT NULL,
    "category_id" TEXT NOT NULL,
    "is_primary" INTEGER NOT NULL DEFAULT 0,
    "added_at" TEXT NOT NULL,
    CONSTRAINT "PK_product_category" PRIMARY KEY ("product_id", "category_id"),
    CONSTRAINT "ck_product_category_is_primary" CHECK (is_primary IN (0,1)),
    CONSTRAINT "FK_product_category_categories_category_id" FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id"),
    CONSTRAINT "FK_product_category_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "products" (
    "product_id" TEXT NOT NULL CONSTRAINT "PK_products" PRIMARY KEY,
    "product_name" TEXT NOT NULL,
    "description" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_products_status" CHECK (status IN ('active','discontinued','archived'))
) STRICT;

CREATE TABLE "promotion_product" (
    "promotion_id" TEXT NOT NULL,
    "product_id" TEXT NOT NULL,
    "valid_from" TEXT NOT NULL,
    "valid_to" TEXT NULL,
    "value_type" TEXT NOT NULL,
    "promotion_value" INTEGER NOT NULL,
    "min_quantity" INTEGER NOT NULL DEFAULT 0,
    "max_redemptions" INTEGER NULL,
    "redemption_count" INTEGER NOT NULL DEFAULT 0,
    "priority" INTEGER NOT NULL DEFAULT 100,
    "is_stackable" INTEGER NOT NULL DEFAULT 0,
    "description" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    CONSTRAINT "PK_promotion_product" PRIMARY KEY ("promotion_id", "product_id", "valid_from"),
    CONSTRAINT "ck_promotion_product_is_stackable" CHECK (is_stackable IN (0,1)),
    CONSTRAINT "ck_promotion_product_promotion_value" CHECK (promotion_value >= 0),
    CONSTRAINT "ck_promotion_product_status" CHECK (status IN ('active','paused','ended')),
    CONSTRAINT "ck_promotion_product_valid_to" CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT "ck_promotion_product_value_type" CHECK (value_type IN ('percent','amount','bogo')),
    CONSTRAINT "ck_promotion_product_value_type_2" CHECK (value_type <> 'percent' OR promotion_value <= 10000),
    CONSTRAINT "FK_promotion_product_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id"),
    CONSTRAINT "FK_promotion_product_promotions_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("promotion_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "promotion_variant" (
    "promotion_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "valid_from" TEXT NOT NULL,
    "valid_to" TEXT NULL,
    "value_type" TEXT NOT NULL,
    "promotion_value" INTEGER NOT NULL,
    "min_quantity" INTEGER NOT NULL DEFAULT 0,
    "max_redemptions" INTEGER NULL,
    "redemption_count" INTEGER NOT NULL DEFAULT 0,
    "priority" INTEGER NOT NULL DEFAULT 100,
    "is_stackable" INTEGER NOT NULL DEFAULT 0,
    "description" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    CONSTRAINT "PK_promotion_variant" PRIMARY KEY ("promotion_id", "variant_id", "valid_from"),
    CONSTRAINT "ck_promotion_variant_is_stackable" CHECK (is_stackable IN (0,1)),
    CONSTRAINT "ck_promotion_variant_promotion_value" CHECK (promotion_value >= 0),
    CONSTRAINT "ck_promotion_variant_status" CHECK (status IN ('active','paused','ended')),
    CONSTRAINT "ck_promotion_variant_valid_to" CHECK (valid_to IS NULL OR valid_to > valid_from),
    CONSTRAINT "ck_promotion_variant_value_type" CHECK (value_type IN ('percent','amount','bogo')),
    CONSTRAINT "ck_promotion_variant_value_type_2" CHECK (value_type <> 'percent' OR promotion_value <= 10000),
    CONSTRAINT "FK_promotion_variant_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id"),
    CONSTRAINT "FK_promotion_variant_promotions_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("promotion_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "promotions" (
    "promotion_id" TEXT NOT NULL CONSTRAINT "PK_promotions" PRIMARY KEY,
    "promotion_name" TEXT NOT NULL,
    "promotion_type" TEXT NOT NULL,
    "store_id" TEXT NULL,
    "source_recommendation_id" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "created_by" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_promotions_promotion_type" CHECK (promotion_type IN ('discount','bogo','bundle','markdown')),
    CONSTRAINT "ck_promotions_status" CHECK (status IN ('draft','scheduled','active','ended','cancelled')),
    CONSTRAINT "FK_promotions_recommendations_source_recommendation_id" FOREIGN KEY ("source_recommendation_id") REFERENCES "recommendations" ("recommendation_id"),
    CONSTRAINT "FK_promotions_staff_created_by" FOREIGN KEY ("created_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_promotions_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "purchase_order_items" (
    "order_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "quantity_ordered" INTEGER NOT NULL,
    "quantity_received" INTEGER NOT NULL DEFAULT 0,
    "purchase_unit_code" TEXT NOT NULL,
    "units_per_purchase_unit" INTEGER NOT NULL DEFAULT 1000,
    "unit_cost" INTEGER NOT NULL,
    "discount" INTEGER NOT NULL DEFAULT 0,
    "line_total" INTEGER NOT NULL,
    CONSTRAINT "PK_purchase_order_items" PRIMARY KEY ("order_id", "variant_id"),
    CONSTRAINT "ck_purchase_order_items_discount" CHECK (discount >= 0),
    CONSTRAINT "ck_purchase_order_items_line_total" CHECK (line_total >= 0),
    CONSTRAINT "ck_purchase_order_items_quantity_ordered" CHECK (quantity_ordered > 0),
    CONSTRAINT "ck_purchase_order_items_quantity_received" CHECK (quantity_received >= 0),
    CONSTRAINT "ck_purchase_order_items_unit_cost" CHECK (unit_cost >= 0),
    CONSTRAINT "FK_purchase_order_items_units_of_measure_purchase_unit_code" FOREIGN KEY ("purchase_unit_code") REFERENCES "units_of_measure" ("unit_code"),
    CONSTRAINT "FK_purchase_order_items_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id"),
    CONSTRAINT "FK_purchase_order_items_purchase_orders_order_id" FOREIGN KEY ("order_id") REFERENCES "purchase_orders" ("order_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "purchase_orders" (
    "order_id" TEXT NOT NULL CONSTRAINT "PK_purchase_orders" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "supplier_id" TEXT NOT NULL,
    "order_date" TEXT NOT NULL,
    "expected_arrival_date" TEXT NULL,
    "received_at" TEXT NULL,
    "total_amount" INTEGER NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "source" TEXT NOT NULL DEFAULT 'manual',
    "source_recommendation_id" TEXT NULL,
    "created_by" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "notes" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_purchase_orders_source" CHECK (source IN ('manual','recommendation','reorder_rule')),
    CONSTRAINT "ck_purchase_orders_status" CHECK (status IN ('draft','sent','partially_received','received','cancelled')),
    CONSTRAINT "FK_purchase_orders_suppliers_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id"),
    CONSTRAINT "FK_purchase_orders_recommendations_source_recommendation_id" FOREIGN KEY ("source_recommendation_id") REFERENCES "recommendations" ("recommendation_id"),
    CONSTRAINT "FK_purchase_orders_staff_created_by" FOREIGN KEY ("created_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_purchase_orders_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "reason_codes" (
    "reason_code" TEXT NOT NULL CONSTRAINT "PK_reason_codes" PRIMARY KEY,
    "applies_to" TEXT NOT NULL,
    "label_ar" TEXT NOT NULL,
    "label_fr" TEXT NOT NULL,
    "requires_note" INTEGER NOT NULL DEFAULT 0,
    "requires_manager" INTEGER NOT NULL DEFAULT 0,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_reason_codes_applies_to" CHECK (applies_to IN ('discount','price_override','adjustment','void', 'return','no_sale','cash_movement','write_off')),
    CONSTRAINT "ck_reason_codes_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "ck_reason_codes_requires_manager" CHECK (requires_manager IN (0,1)),
    CONSTRAINT "ck_reason_codes_requires_note" CHECK (requires_note IN (0,1))
) STRICT;

CREATE TABLE "recommendation_decisions" (
    "decision_id" TEXT NOT NULL CONSTRAINT "PK_recommendation_decisions" PRIMARY KEY,
    "recommendation_id" TEXT NOT NULL,
    "decision" TEXT NOT NULL,
    "chosen_option_id" TEXT NULL,
    "adjusted_payload_json" TEXT NULL,
    "snooze_until" TEXT NULL,
    "origin" TEXT NOT NULL,
    "decided_by" TEXT NULL,
    "decided_at" TEXT NOT NULL,
    "terminal_id" TEXT NULL,
    "applied_at" TEXT NULL,
    "resulting_entity_type" TEXT NULL,
    "resulting_entity_id" TEXT NULL,
    CONSTRAINT "ck_recommendation_decisions_decision" CHECK (decision IN ('accept','adjust','dismiss','snooze')),
    CONSTRAINT "ck_recommendation_decisions_decision_2" CHECK (decision <> 'snooze' OR snooze_until IS NOT NULL),
    CONSTRAINT "ck_recommendation_decisions_decision_3" CHECK (decision <> 'adjust' OR adjusted_payload_json IS NOT NULL),
    CONSTRAINT "ck_recommendation_decisions_origin" CHECK (origin IN ('store','cloud')),
    CONSTRAINT "FK_recommendation_decisions_recommendation_options_chosen_option_id" FOREIGN KEY ("chosen_option_id") REFERENCES "recommendation_options" ("option_id"),
    CONSTRAINT "FK_recommendation_decisions_recommendations_recommendation_id" FOREIGN KEY ("recommendation_id") REFERENCES "recommendations" ("recommendation_id"),
    CONSTRAINT "FK_recommendation_decisions_staff_decided_by" FOREIGN KEY ("decided_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_recommendation_decisions_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id")
) STRICT;

CREATE TABLE "recommendation_options" (
    "option_id" TEXT NOT NULL CONSTRAINT "PK_recommendation_options" PRIMARY KEY,
    "recommendation_id" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "display_order" INTEGER NOT NULL DEFAULT 0,
    "payload_json" TEXT NOT NULL,
    "projected_value" INTEGER NULL,
    CONSTRAINT "FK_recommendation_options_recommendations_recommendation_id" FOREIGN KEY ("recommendation_id") REFERENCES "recommendations" ("recommendation_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "recommendations" (
    "recommendation_id" TEXT NOT NULL CONSTRAINT "PK_recommendations" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "urgency" TEXT NOT NULL,
    "action_type" TEXT NOT NULL,
    "subject_type" TEXT NOT NULL,
    "subject_id" TEXT NOT NULL,
    "headline" TEXT NOT NULL,
    "because_json" TEXT NOT NULL,
    "interval_low" INTEGER NULL,
    "interval_high" INTEGER NULL,
    "computed_at" TEXT NOT NULL,
    "parameter_version" INTEGER NULL,
    "source" TEXT NOT NULL,
    "minimum_required_role" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "issued_at" TEXT NOT NULL,
    "delivered_at" TEXT NULL,
    "expires_at" TEXT NULL, "recommendation_type" TEXT NOT NULL DEFAULT '',
    CONSTRAINT "ck_recommendations_action_type" CHECK (action_type IN ('binary','menu')),
    CONSTRAINT "ck_recommendations_department" CHECK (department IN ('inventory','sales_demand','supply','planning','customer')),
    CONSTRAINT "ck_recommendations_interval_low" CHECK (interval_low IS NULL OR interval_high IS NULL OR interval_high >= interval_low),
    CONSTRAINT "ck_recommendations_status" CHECK (status IN ('pending','delivered','decided','expired','superseded')),
    CONSTRAINT "ck_recommendations_subject_type" CHECK (subject_type IN ('variant','batch','product','supplier','customer','store')),
    CONSTRAINT "ck_recommendations_urgency" CHECK (urgency IN ('quiet','standard','warning','critical')),
    CONSTRAINT "FK_recommendations_roles_minimum_required_role" FOREIGN KEY ("minimum_required_role") REFERENCES "roles" ("role_code"),
    CONSTRAINT "FK_recommendations_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "retention_policies" (
    "policy_code" TEXT NOT NULL CONSTRAINT "PK_retention_policies" PRIMARY KEY,
    "entity_type" TEXT NOT NULL,
    "retention_days" INTEGER NOT NULL,
    "legal_basis_reference" TEXT NOT NULL,
    "action_on_expiry" TEXT NOT NULL,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_retention_policies_action_on_expiry" CHECK (action_on_expiry IN ('delete','unlink','archive')),
    CONSTRAINT "ck_retention_policies_entity_type" CHECK (entity_type IN ('transaction','customer','staff','processing_log', 'consent_event','recommendation','stock_movement')),
    CONSTRAINT "ck_retention_policies_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "ck_retention_policies_retention_days" CHECK (retention_days > 0)
) STRICT;

CREATE TABLE "returns" (
    "return_id" TEXT NOT NULL CONSTRAINT "PK_returns" PRIMARY KEY,
    "transaction_item_id" TEXT NOT NULL,
    "store_id" TEXT NOT NULL,
    "terminal_id" TEXT NULL,
    "batch_id" TEXT NULL,
    "staff_id" TEXT NOT NULL,
    "approved_by" TEXT NULL,
    "quantity_returned" INTEGER NOT NULL,
    "refund_amount" INTEGER NOT NULL,
    "refund_method" TEXT NOT NULL,
    "restock_flag" INTEGER NOT NULL,
    "reason_code" TEXT NOT NULL,
    "note" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_returns_quantity_returned" CHECK (quantity_returned > 0),
    CONSTRAINT "ck_returns_refund_amount" CHECK (refund_amount >= 0),
    CONSTRAINT "ck_returns_refund_method" CHECK (refund_method IN ('cash','card','store_credit','exchange')),
    CONSTRAINT "ck_returns_restock_flag" CHECK (restock_flag IN (0,1)),
    CONSTRAINT "FK_returns_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id"),
    CONSTRAINT "FK_returns_reason_codes_reason_code" FOREIGN KEY ("reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_returns_staff_approved_by" FOREIGN KEY ("approved_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_returns_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_returns_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_returns_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id"),
    CONSTRAINT "FK_returns_transaction_items_transaction_item_id" FOREIGN KEY ("transaction_item_id") REFERENCES "transaction_items" ("transaction_item_id")
) STRICT;

CREATE TABLE "roles" (
    "role_code" TEXT NOT NULL CONSTRAINT "PK_roles" PRIMARY KEY,
    "rank" INTEGER NOT NULL,
    "label_ar" TEXT NOT NULL,
    "label_fr" TEXT NOT NULL,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_roles_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "ck_roles_rank" CHECK (rank > 0)
) STRICT;

CREATE TABLE "rounding_variance" (
    "variance_id" TEXT NOT NULL CONSTRAINT "PK_rounding_variance" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "occurred_at" TEXT NOT NULL,
    "reference_type" TEXT NOT NULL,
    "reference_id" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "policy" TEXT NOT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_rounding_variance_amount" CHECK (amount <> 0),
    CONSTRAINT "ck_rounding_variance_policy" CHECK (policy IN ('half_even','half_up')),
    CONSTRAINT "ck_rounding_variance_reference_type" CHECK (reference_type IN ('transaction','purchase_order','batch')),
    CONSTRAINT "ck_rounding_variance_source" CHECK (source IN ('cash_tender','currency_conversion')),
    CONSTRAINT "FK_rounding_variance_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "schema_migrations" (
    "version" TEXT NOT NULL CONSTRAINT "PK_schema_migrations" PRIMARY KEY,
    "description" TEXT NOT NULL,
    "applied_at" TEXT NOT NULL
) STRICT;

CREATE TABLE "shifts" (
    "shift_id" TEXT NOT NULL CONSTRAINT "PK_shifts" PRIMARY KEY,
    "staff_id" TEXT NOT NULL,
    "terminal_id" TEXT NULL,
    "store_id" TEXT NOT NULL,
    "start_time" TEXT NOT NULL,
    "end_time" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_shifts_end_time" CHECK (end_time IS NULL OR end_time >= start_time),
    CONSTRAINT "ck_shifts_status" CHECK (status IN ('open','closed')),
    CONSTRAINT "FK_shifts_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_shifts_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_shifts_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id")
) STRICT;

CREATE TABLE "staff" (
    "staff_id" TEXT NOT NULL CONSTRAINT "PK_staff" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "staff_name" TEXT NOT NULL,
    "contact_phone" TEXT NULL,
    "email" TEXT NULL,
    "role" TEXT NOT NULL,
    "pin_hash" TEXT NOT NULL,
    "join_date" TEXT NOT NULL,
    "last_seen_date" TEXT NULL,
    "termination_date" TEXT NULL,
    "notice_version_acknowledged" TEXT NULL,
    "notice_acknowledged_at" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_staff_status" CHECK (status IN ('active','suspended','terminated')),
    CONSTRAINT "FK_staff_notice_versions_notice_version_acknowledged" FOREIGN KEY ("notice_version_acknowledged") REFERENCES "notice_versions" ("version_code"),
    CONSTRAINT "FK_staff_roles_role" FOREIGN KEY ("role") REFERENCES "roles" ("role_code"),
    CONSTRAINT "FK_staff_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "stock_count_items" (
    "count_item_id" TEXT NOT NULL CONSTRAINT "PK_stock_count_items" PRIMARY KEY,
    "count_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "batch_id" TEXT NOT NULL,
    "expected_quantity" INTEGER NOT NULL,
    "counted_quantity" INTEGER NULL,
    "variance_quantity" INTEGER NULL,
    "unit_cost" INTEGER NULL,
    "variance_value" INTEGER NULL,
    "counted_by" TEXT NULL,
    "counted_at" TEXT NULL,
    "recount_flag" INTEGER NOT NULL DEFAULT 0,
    "note" TEXT NULL,
    CONSTRAINT "ck_stock_count_items_recount_flag" CHECK (recount_flag IN (0,1)),
    CONSTRAINT "FK_stock_count_items_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id"),
    CONSTRAINT "FK_stock_count_items_staff_counted_by" FOREIGN KEY ("counted_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_stock_count_items_stock_counts_count_id" FOREIGN KEY ("count_id") REFERENCES "stock_counts" ("count_id") ON DELETE CASCADE,
    CONSTRAINT "FK_stock_count_items_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id")
) STRICT;

CREATE TABLE "stock_counts" (
    "count_id" TEXT NOT NULL CONSTRAINT "PK_stock_counts" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "count_type" TEXT NOT NULL,
    "scope_category_id" TEXT NULL,
    "started_by" TEXT NOT NULL,
    "started_at" TEXT NOT NULL,
    "completed_at" TEXT NULL,
    "approved_by" TEXT NULL,
    "approved_at" TEXT NULL,
    "total_variance_value" INTEGER NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "notes" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_stock_counts_count_type" CHECK (count_type IN ('full','cycle','spot')),
    CONSTRAINT "ck_stock_counts_status" CHECK (status IN ('draft','counting','review','posted','cancelled')),
    CONSTRAINT "ck_stock_counts_status_2" CHECK (status <> 'posted' OR approved_by IS NOT NULL),
    CONSTRAINT "FK_stock_counts_categories_scope_category_id" FOREIGN KEY ("scope_category_id") REFERENCES "categories" ("category_id"),
    CONSTRAINT "FK_stock_counts_staff_approved_by" FOREIGN KEY ("approved_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_stock_counts_staff_started_by" FOREIGN KEY ("started_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_stock_counts_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "stock_movements" (
    "movement_id" TEXT NOT NULL CONSTRAINT "PK_stock_movements" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "batch_id" TEXT NOT NULL,
    "movement_date" TEXT NOT NULL,
    "movement_type" TEXT NOT NULL,
    "quantity_changed" INTEGER NOT NULL,
    "unit_code" TEXT NOT NULL,
    "unit_cost" INTEGER NULL,
    "reference_type" TEXT NULL,
    "reference_id" TEXT NULL,
    "reason_code" TEXT NULL,
    "staff_id" TEXT NULL,
    "note" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_stock_movements_movement_type" CHECK (movement_type IN ('receipt','sale','return_in','return_out', 'adjustment','count','write_off','expiry','transfer')),
    CONSTRAINT "ck_stock_movements_quantity_changed" CHECK (quantity_changed <> 0),
    CONSTRAINT "ck_stock_movements_reference_type" CHECK (reference_type IS NULL OR reference_type IN ('transaction','purchase_order','stock_count','return','manual')),
    CONSTRAINT "FK_stock_movements_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id"),
    CONSTRAINT "FK_stock_movements_reason_codes_reason_code" FOREIGN KEY ("reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_stock_movements_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_stock_movements_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_stock_movements_units_of_measure_unit_code" FOREIGN KEY ("unit_code") REFERENCES "units_of_measure" ("unit_code"),
    CONSTRAINT "FK_stock_movements_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id")
) STRICT;

CREATE TABLE "store_entitlements" (
    "entitlement_code" TEXT NOT NULL CONSTRAINT "PK_store_entitlements" PRIMARY KEY,
    "is_enabled" INTEGER NOT NULL DEFAULT 0,
    "tier" TEXT NULL,
    "valid_from" TEXT NULL,
    "valid_to" TEXT NULL,
    "synced_at" TEXT NOT NULL,
    CONSTRAINT "ck_store_entitlements_is_enabled" CHECK (is_enabled IN (0,1)),
    CONSTRAINT "ck_store_entitlements_tier" CHECK (tier IN ('basic','pro','enterprise'))
) STRICT;

CREATE TABLE "stores" (
    "store_id" TEXT NOT NULL CONSTRAINT "PK_stores" PRIMARY KEY,
    "store_code" TEXT NOT NULL,
    "store_name" TEXT NOT NULL,
    "contact_phone" TEXT NULL,
    "email" TEXT NULL,
    "address" TEXT NULL,
    "latitude" TEXT NULL,
    "longitude" TEXT NULL,
    "store_type" TEXT NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "timezone" TEXT NOT NULL DEFAULT 'Africa/Algiers',
    "tax_registration_number" TEXT NULL,
    "fiscal_year_start" TEXT NOT NULL DEFAULT '01-01',
    "manager_id" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_stores_status" CHECK (status IN ('active','suspended','closed')),
    CONSTRAINT "FK_stores_staff_manager_id" FOREIGN KEY ("manager_id") REFERENCES "staff" ("staff_id")
) STRICT;

CREATE TABLE "supplier_variant" (
    "supplier_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "purchase_unit_code" TEXT NOT NULL,
    "units_per_purchase_unit" INTEGER NOT NULL DEFAULT 1000,
    "minimum_order_quantity" INTEGER NOT NULL DEFAULT 0,
    "stated_lead_time_days" INTEGER NULL,
    "purchase_price" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "net_days" INTEGER NULL,
    "last_price_at" TEXT NULL,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "PK_supplier_variant" PRIMARY KEY ("supplier_id", "variant_id"),
    CONSTRAINT "ck_supplier_variant_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "ck_supplier_variant_purchase_price" CHECK (purchase_price >= 0),
    CONSTRAINT "ck_supplier_variant_stated_lead_time_days" CHECK (stated_lead_time_days IS NULL OR stated_lead_time_days >= 0),
    CONSTRAINT "ck_supplier_variant_units_per_purchase_unit" CHECK (units_per_purchase_unit > 0),
    CONSTRAINT "FK_supplier_variant_suppliers_supplier_id" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id"),
    CONSTRAINT "FK_supplier_variant_units_of_measure_purchase_unit_code" FOREIGN KEY ("purchase_unit_code") REFERENCES "units_of_measure" ("unit_code"),
    CONSTRAINT "FK_supplier_variant_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id")
) STRICT;

CREATE TABLE "suppliers" (
    "supplier_id" TEXT NOT NULL CONSTRAINT "PK_suppliers" PRIMARY KEY,
    "supplier_code" TEXT NOT NULL,
    "company_name" TEXT NOT NULL,
    "responsible_name" TEXT NULL,
    "contact_phone" TEXT NULL,
    "email" TEXT NULL,
    "website" TEXT NULL,
    "shipping_address" TEXT NULL,
    "net_days" INTEGER NOT NULL DEFAULT 0,
    "credit_limit" INTEGER NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_suppliers_net_days" CHECK (net_days >= 0),
    CONSTRAINT "ck_suppliers_status" CHECK (status IN ('active','inactive','blacklisted'))
) STRICT;

CREATE TABLE "sync_state" (
    "state_key" TEXT NOT NULL CONSTRAINT "PK_sync_state" PRIMARY KEY,
    "state_value" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL
) STRICT;

CREATE TABLE "system_config" (
    "config_key" TEXT NOT NULL CONSTRAINT "PK_system_config" PRIMARY KEY,
    "config_value" TEXT NOT NULL,
    "data_type" TEXT NOT NULL,
    "description" TEXT NULL,
    "updated_by" TEXT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_system_config_data_type" CHECK (data_type IN ('text','integer','money','percent','bool','date'))
) STRICT;

CREATE TABLE "terminals" (
    "terminal_id" TEXT NOT NULL CONSTRAINT "PK_terminals" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "terminal_name" TEXT NOT NULL,
    "is_replica" INTEGER NOT NULL DEFAULT 0,
    "printer_port" TEXT NULL,
    "hardware_notes" TEXT NULL,
    "last_seen_at" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_terminals_is_replica" CHECK (is_replica IN (0,1)),
    CONSTRAINT "ck_terminals_status" CHECK (status IN ('active','inactive','retired')),
    CONSTRAINT "FK_terminals_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id")
) STRICT;

CREATE TABLE "transaction_items" (
    "transaction_item_id" TEXT NOT NULL CONSTRAINT "PK_transaction_items" PRIMARY KEY,
    "transaction_id" TEXT NOT NULL,
    "variant_id" TEXT NOT NULL,
    "batch_id" TEXT NULL,
    "promotion_id" TEXT NULL,
    "quantity" INTEGER NOT NULL,
    "unit_code" TEXT NOT NULL,
    "sell_price" INTEGER NOT NULL,
    "unit_cost_at_sale" INTEGER NULL,
    "discount_amount" INTEGER NOT NULL DEFAULT 0,
    "discount_reason_code" TEXT NULL,
    "authorised_by" TEXT NULL,
    "tax_amount" INTEGER NOT NULL DEFAULT 0,
    "line_total" INTEGER NOT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_transaction_items_discount_amount" CHECK (discount_amount >= 0),
    CONSTRAINT "ck_transaction_items_discount_amount_2" CHECK (discount_amount = 0 OR discount_reason_code IS NOT NULL),
    CONSTRAINT "ck_transaction_items_quantity" CHECK (quantity <> 0),
    CONSTRAINT "ck_transaction_items_sell_price" CHECK (sell_price >= 0),
    CONSTRAINT "FK_transaction_items_batches_batch_id" FOREIGN KEY ("batch_id") REFERENCES "batches" ("batch_id"),
    CONSTRAINT "FK_transaction_items_promotions_promotion_id" FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("promotion_id"),
    CONSTRAINT "FK_transaction_items_reason_codes_discount_reason_code" FOREIGN KEY ("discount_reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_transaction_items_staff_authorised_by" FOREIGN KEY ("authorised_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_transaction_items_transactions_transaction_id" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id"),
    CONSTRAINT "FK_transaction_items_units_of_measure_unit_code" FOREIGN KEY ("unit_code") REFERENCES "units_of_measure" ("unit_code"),
    CONSTRAINT "FK_transaction_items_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id")
) STRICT;

CREATE TABLE "transaction_payments" (
    "payment_id" TEXT NOT NULL CONSTRAINT "PK_transaction_payments" PRIMARY KEY,
    "transaction_id" TEXT NOT NULL,
    "sequence" INTEGER NOT NULL,
    "payment_method" TEXT NOT NULL,
    "amount" INTEGER NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "reference" TEXT NULL,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_transaction_payments_amount" CHECK (amount <> 0),
    CONSTRAINT "ck_transaction_payments_payment_method" CHECK (payment_method IN ('cash','card','mobile_wallet','store_credit','on_account')),
    CONSTRAINT "FK_transaction_payments_transactions_transaction_id" FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("transaction_id")
) STRICT;

CREATE TABLE "transactions" (
    "transaction_id" TEXT NOT NULL CONSTRAINT "PK_transactions" PRIMARY KEY,
    "store_id" TEXT NOT NULL,
    "terminal_id" TEXT NOT NULL,
    "cash_session_id" TEXT NULL,
    "staff_id" TEXT NOT NULL,
    "customer_id" TEXT NULL,
    "invoice_number" TEXT NULL,
    "occurred_at" TEXT NOT NULL,
    "subtotal" INTEGER NOT NULL DEFAULT 0,
    "discount_total" INTEGER NOT NULL DEFAULT 0,
    "tax_total" INTEGER NOT NULL DEFAULT 0,
    "total_amount" INTEGER NOT NULL DEFAULT 0,
    "currency" TEXT NOT NULL DEFAULT 'DZD',
    "ecommerce_flag" INTEGER NOT NULL DEFAULT 0,
    "original_transaction_id" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'open',
    "voided_at" TEXT NULL,
    "voided_by" TEXT NULL,
    "void_reason_code" TEXT NULL,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_transactions_ecommerce_flag" CHECK (ecommerce_flag IN (0,1)),
    CONSTRAINT "ck_transactions_status" CHECK (status IN ('open','parked','completed','voided','refunded','partially_refunded')),
    CONSTRAINT "ck_transactions_status_2" CHECK (status <> 'voided' OR (voided_at IS NOT NULL AND void_reason_code IS NOT NULL)),
    CONSTRAINT "ck_transactions_status_3" CHECK (status <> 'completed' OR invoice_number IS NOT NULL),
    CONSTRAINT "FK_transactions_cash_sessions_cash_session_id" FOREIGN KEY ("cash_session_id") REFERENCES "cash_sessions" ("session_id"),
    CONSTRAINT "FK_transactions_customers_customer_id" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id"),
    CONSTRAINT "FK_transactions_reason_codes_void_reason_code" FOREIGN KEY ("void_reason_code") REFERENCES "reason_codes" ("reason_code"),
    CONSTRAINT "FK_transactions_staff_staff_id" FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_transactions_staff_voided_by" FOREIGN KEY ("voided_by") REFERENCES "staff" ("staff_id"),
    CONSTRAINT "FK_transactions_stores_store_id" FOREIGN KEY ("store_id") REFERENCES "stores" ("store_id"),
    CONSTRAINT "FK_transactions_terminals_terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "terminals" ("terminal_id"),
    CONSTRAINT "FK_transactions_transactions_original_transaction_id" FOREIGN KEY ("original_transaction_id") REFERENCES "transactions" ("transaction_id")
) STRICT;

CREATE TABLE "units_of_measure" (
    "unit_code" TEXT NOT NULL CONSTRAINT "PK_units_of_measure" PRIMARY KEY,
    "name_ar" TEXT NOT NULL,
    "name_fr" TEXT NOT NULL,
    "dimension" TEXT NOT NULL,
    "base_unit_code" TEXT NULL,
    "factor_to_base" INTEGER NOT NULL DEFAULT 1000000,
    "decimal_places" INTEGER NOT NULL DEFAULT 0,
    "is_active" INTEGER NOT NULL DEFAULT 1,
    "created_at" TEXT NOT NULL,
    CONSTRAINT "ck_units_of_measure_decimal_places" CHECK (decimal_places BETWEEN 0 AND 3),
    CONSTRAINT "ck_units_of_measure_dimension" CHECK (dimension IN ('count','weight','volume','length')),
    CONSTRAINT "ck_units_of_measure_factor_to_base" CHECK (factor_to_base > 0),
    CONSTRAINT "ck_units_of_measure_is_active" CHECK (is_active IN (0,1)),
    CONSTRAINT "FK_units_of_measure_units_of_measure_base_unit_code" FOREIGN KEY ("base_unit_code") REFERENCES "units_of_measure" ("unit_code")
) STRICT;

CREATE TABLE "variant_attribute_values" (
    "variant_id" TEXT NOT NULL,
    "attribute_code" TEXT NOT NULL,
    "value_text" TEXT NULL,
    "value_number" INTEGER NULL,
    "value_bool" INTEGER NULL,
    "value_date" TEXT NULL,
    "option_code" TEXT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "PK_variant_attribute_values" PRIMARY KEY ("variant_id", "attribute_code"),
    CONSTRAINT "ck_variant_attribute_values_CASE" CHECK ((CASE WHEN value_text IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_number IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_bool IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN value_date IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN option_code IS NOT NULL THEN 1 ELSE 0 END) = 1),
    CONSTRAINT "ck_variant_attribute_values_value_bool" CHECK (value_bool IS NULL OR value_bool IN (0,1)),
    CONSTRAINT "FK_variant_attribute_values_attribute_definitions_attribute_code" FOREIGN KEY ("attribute_code") REFERENCES "attribute_definitions" ("attribute_code"),
    CONSTRAINT "FK_variant_attribute_values_attribute_options_attribute_code_option_code" FOREIGN KEY ("attribute_code", "option_code") REFERENCES "attribute_options" ("attribute_code", "option_code"),
    CONSTRAINT "FK_variant_attribute_values_variants_variant_id" FOREIGN KEY ("variant_id") REFERENCES "variants" ("variant_id") ON DELETE CASCADE
) STRICT;

CREATE TABLE "variants" (
    "variant_id" TEXT NOT NULL CONSTRAINT "PK_variants" PRIMARY KEY,
    "product_id" TEXT NOT NULL,
    "variant_name" TEXT NOT NULL,
    "barcode" TEXT NULL,
    "plu" TEXT NULL,
    "sku" TEXT NULL,
    "barcode_type" TEXT NOT NULL DEFAULT 'standard',
    "selling_unit_code" TEXT NOT NULL,
    "is_weighted" INTEGER NOT NULL DEFAULT 0,
    "tare_weight" INTEGER NOT NULL DEFAULT 0,
    "image" TEXT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    CONSTRAINT "ck_variants_barcode_type" CHECK (barcode_type IN ('standard', 'weight_embedded', 'price_embedded')),
    CONSTRAINT "ck_variants_is_weighted" CHECK (is_weighted IN (0,1)),
    CONSTRAINT "ck_variants_is_weighted_2" CHECK (is_weighted = 0 OR plu IS NOT NULL OR barcode IS NOT NULL),
    CONSTRAINT "ck_variants_status" CHECK (status IN ('active','discontinued','archived')),
    CONSTRAINT "ck_variants_tare_weight" CHECK (tare_weight >= 0),
    CONSTRAINT "FK_variants_products_product_id" FOREIGN KEY ("product_id") REFERENCES "products" ("product_id"),
    CONSTRAINT "FK_variants_units_of_measure_selling_unit_code" FOREIGN KEY ("selling_unit_code") REFERENCES "units_of_measure" ("unit_code")
) STRICT;


-- =============================================================================
-- INDEXES
-- =============================================================================

CREATE UNIQUE INDEX "IX_categories_slug" ON "categories" ("slug");

CREATE UNIQUE INDEX "IX_inbox_message_id" ON "inbox" ("message_id");

CREATE UNIQUE INDEX "IX_outbox_sequence_number" ON "outbox" ("sequence_number");

CREATE UNIQUE INDEX "IX_product_bundles_barcode" ON "product_bundles" ("barcode");

CREATE UNIQUE INDEX "IX_recommendation_options_recommendation_id_display_order" ON "recommendation_options" ("recommendation_id", "display_order");

CREATE UNIQUE INDEX "IX_roles_rank" ON "roles" ("rank");

CREATE UNIQUE INDEX "IX_stock_count_items_count_id_variant_id_batch_id" ON "stock_count_items" ("count_id", "variant_id", "batch_id");

CREATE UNIQUE INDEX "IX_stores_store_code" ON "stores" ("store_code");

CREATE UNIQUE INDEX "IX_suppliers_supplier_code" ON "suppliers" ("supplier_code");

CREATE UNIQUE INDEX "IX_transaction_payments_transaction_id_sequence" ON "transaction_payments" ("transaction_id", "sequence");

CREATE UNIQUE INDEX "IX_variants_barcode" ON "variants" ("barcode");

CREATE UNIQUE INDEX "IX_variants_plu" ON "variants" ("plu");

CREATE UNIQUE INDEX "IX_variants_sku" ON "variants" ("sku");

CREATE INDEX "ix_batch_items_variant" ON "batch_items" ("variant_id");

CREATE INDEX "ix_batches_expiry" ON "batches" ("store_id", "expiration_date") WHERE expiration_date IS NOT NULL AND status = 'active';

CREATE INDEX "ix_batches_order" ON "batches" ("order_id");

CREATE INDEX "ix_batches_product" ON "batches" ("product_id");

CREATE INDEX "ix_bundle_items_variant" ON "product_bundle_items" ("variant_id");

CREATE INDEX "ix_cash_movements_session" ON "cash_movements" ("session_id");

CREATE INDEX "ix_cash_sessions_open" ON "cash_sessions" ("store_id") WHERE status = 'open';

CREATE INDEX "ix_cash_sessions_terminal" ON "cash_sessions" ("terminal_id", "opened_at");

CREATE INDEX "ix_categories_parent" ON "categories" ("parent_id");

CREATE INDEX "ix_category_attr_attribute" ON "category_attributes" ("attribute_code");

CREATE INDEX "ix_consent_customer" ON "consent_events" ("customer_id", "occurred_at");

CREATE INDEX "ix_count_items_count" ON "stock_count_items" ("count_id");

CREATE INDEX "ix_credit_customer" ON "credit_movements" ("customer_id", "occurred_at");

CREATE INDEX "ix_customers_phone" ON "customers" ("contact_phone");

CREATE INDEX "ix_dsr_customer" ON "data_subject_requests" ("customer_id");

CREATE INDEX "ix_dsr_open" ON "data_subject_requests" ("due_at") WHERE status IN ('open','in_progress');

CREATE INDEX "ix_erasure_subject" ON "erasure_ledger" ("subject_type", "subject_id");

CREATE INDEX "ix_inbox_pending" ON "inbox" ("status", "cloud_sequence") WHERE status = 'pending';

CREATE INDEX "ix_intents_expiry" ON "intents" ("expires_at") WHERE status = 'pending';

CREATE INDEX "ix_intents_pending" ON "intents" ("store_id", "status") WHERE status = 'pending';

CREATE INDEX "ix_inventories_batch" ON "inventories" ("batch_id");

CREATE INDEX "ix_inventories_variant" ON "inventories" ("variant_id", "store_id");

CREATE INDEX "ix_loyalty_customer" ON "loyalty_movements" ("customer_id", "occurred_at");

CREATE INDEX "ix_movements_batch" ON "stock_movements" ("batch_id");

CREATE INDEX "ix_movements_reference" ON "stock_movements" ("reference_type", "reference_id");

CREATE INDEX "ix_movements_store_date" ON "stock_movements" ("store_id", "movement_date");

CREATE INDEX "ix_movements_variant_date" ON "stock_movements" ("variant_id", "movement_date");

CREATE INDEX "ix_outbox_drain" ON "outbox" ("is_priority", "sequence_number");

CREATE INDEX "ix_pav_attribute" ON "product_attribute_values" ("attribute_code");

CREATE INDEX "ix_payments_method" ON "transaction_payments" ("payment_method", "created_at");

CREATE INDEX "ix_payments_transaction" ON "transaction_payments" ("transaction_id");

CREATE INDEX "ix_po_items_variant" ON "purchase_order_items" ("variant_id");

CREATE INDEX "ix_po_store_status" ON "purchase_orders" ("store_id", "status");

CREATE INDEX "ix_po_supplier" ON "purchase_orders" ("supplier_id");

CREATE INDEX "ix_prices_lookup" ON "prices" ("variant_id", "store_id", "valid_from");

CREATE INDEX "ix_proclog_occurred" ON "processing_log" ("occurred_at");

CREATE INDEX "ix_proclog_subject" ON "processing_log" ("subject_type", "subject_id", "occurred_at");

CREATE INDEX "ix_product_category_cat" ON "product_category" ("category_id");

CREATE INDEX "ix_promo_product_product" ON "promotion_product" ("product_id");

CREATE INDEX "ix_promo_variant_variant" ON "promotion_variant" ("variant_id");

CREATE INDEX "ix_promotions_status" ON "promotions" ("status", "store_id");

CREATE INDEX "ix_rec_decisions_date" ON "recommendation_decisions" ("decided_at");

CREATE INDEX "ix_rec_decisions_rec" ON "recommendation_decisions" ("recommendation_id");

CREATE INDEX "ix_rec_options_rec" ON "recommendation_options" ("recommendation_id");

CREATE INDEX "ix_recs_dedupe" ON "recommendations" ("store_id", "recommendation_type", "subject_type", "subject_id");

CREATE INDEX "ix_recs_pending" ON "recommendations" ("store_id", "status", "urgency") WHERE status IN ('pending','delivered');

CREATE INDEX "ix_recs_subject" ON "recommendations" ("subject_type", "subject_id");

CREATE INDEX "ix_returns_item" ON "returns" ("transaction_item_id");

CREATE INDEX "ix_returns_store_date" ON "returns" ("store_id", "created_at");

CREATE INDEX "ix_rounding_variance_reference" ON "rounding_variance" ("reference_type", "reference_id");

CREATE INDEX "ix_rounding_variance_store_date" ON "rounding_variance" ("store_id", "occurred_at");

CREATE INDEX "ix_shifts_staff" ON "shifts" ("staff_id", "start_time");

CREATE INDEX "ix_shifts_store_open" ON "shifts" ("store_id") WHERE status = 'open';

CREATE INDEX "ix_staff_store" ON "staff" ("store_id", "status");

CREATE INDEX "ix_stock_counts_store" ON "stock_counts" ("store_id", "status");

CREATE INDEX "ix_supplier_variant_variant" ON "supplier_variant" ("variant_id");

CREATE INDEX "ix_terminals_store" ON "terminals" ("store_id");

CREATE INDEX "ix_transactions_customer" ON "transactions" ("customer_id") WHERE customer_id IS NOT NULL;

CREATE INDEX "ix_transactions_original" ON "transactions" ("original_transaction_id");

CREATE INDEX "ix_transactions_session" ON "transactions" ("cash_session_id");

CREATE INDEX "ix_transactions_staff" ON "transactions" ("staff_id", "occurred_at");

CREATE INDEX "ix_transactions_store_date" ON "transactions" ("store_id", "occurred_at");

CREATE INDEX "ix_txn_items_batch" ON "transaction_items" ("batch_id");

CREATE INDEX "ix_txn_items_transaction" ON "transaction_items" ("transaction_id");

CREATE INDEX "ix_txn_items_variant" ON "transaction_items" ("variant_id", "created_at");

CREATE INDEX "ix_variants_product" ON "variants" ("product_id");

CREATE INDEX "ix_variants_status" ON "variants" ("status");

CREATE INDEX "ix_vav_attribute" ON "variant_attribute_values" ("attribute_code");

CREATE UNIQUE INDEX "ux_parameter_current" ON "parameter_registry" ("parameter_code", "scope_type", "scope_id") WHERE is_current = 1;

CREATE UNIQUE INDEX "ux_processing_counters_day" ON "processing_counters" ("store_id", "day", "operation", "purpose");

CREATE UNIQUE INDEX "ux_product_category_primary" ON "product_category" ("product_id") WHERE is_primary = 1;

CREATE UNIQUE INDEX "ux_transactions_invoice" ON "transactions" ("store_id", "invoice_number") WHERE invoice_number IS NOT NULL;


-- =============================================================================
-- TRIGGERS
-- =============================================================================

CREATE TRIGGER trg_consent_events_no_delete
BEFORE DELETE ON consent_events
BEGIN
    SELECT RAISE(ABORT, 'consent_events is append-only');
END;

CREATE TRIGGER trg_consent_events_no_update
BEFORE UPDATE ON consent_events
BEGIN
    SELECT RAISE(ABORT, 'consent_events is append-only: withdrawal is a new event');
END;

CREATE TRIGGER trg_credit_movements_no_delete
BEFORE DELETE ON credit_movements
BEGIN
    SELECT RAISE(ABORT, 'credit_movements is append-only');
END;

CREATE TRIGGER trg_credit_movements_no_update
BEFORE UPDATE ON credit_movements
BEGIN
    SELECT RAISE(ABORT, 'credit_movements is append-only: post a reversing movement');
END;

CREATE TRIGGER trg_erasure_ledger_no_delete
BEFORE DELETE ON erasure_ledger
BEGIN
    SELECT RAISE(ABORT, 'erasure_ledger is the evidence of compliance and cannot be deleted');
END;

CREATE TRIGGER trg_loyalty_movements_no_delete
BEFORE DELETE ON loyalty_movements
BEGIN
    SELECT RAISE(ABORT, 'loyalty_movements is append-only');
END;

CREATE TRIGGER trg_loyalty_movements_no_update
BEFORE UPDATE ON loyalty_movements
BEGIN
    SELECT RAISE(ABORT, 'loyalty_movements is append-only: post a reversing movement');
END;

CREATE TRIGGER trg_rec_decisions_no_delete
BEFORE DELETE ON recommendation_decisions
BEGIN
    SELECT RAISE(ABORT, 'recommendation_decisions is append-only');
END;

CREATE TRIGGER trg_rec_decisions_no_update
BEFORE UPDATE ON recommendation_decisions
    WHEN OLD.applied_at IS NOT NULL
BEGIN
    SELECT RAISE(ABORT, 'a decision cannot be changed once applied');
END;

CREATE TRIGGER trg_rounding_variance_no_delete
BEFORE DELETE ON rounding_variance
BEGIN
    SELECT RAISE(ABORT, 'rounding_variance is append-only');
END;

CREATE TRIGGER trg_rounding_variance_no_update
BEFORE UPDATE ON rounding_variance
BEGIN
    SELECT RAISE(ABORT, 'rounding_variance is append-only: post a correcting row');
END;

CREATE TRIGGER trg_stock_movements_no_delete
BEFORE DELETE ON stock_movements
BEGIN
    SELECT RAISE(ABORT, 'stock_movements is append-only');
END;

CREATE TRIGGER trg_stock_movements_no_update
BEFORE UPDATE ON stock_movements
BEGIN
    SELECT RAISE(ABORT, 'stock_movements is append-only: post a correcting movement');
END;
